#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.xyz"
cmd="xdg-open"
EWW="eww"

if [[ "$1" == "--firefox" ]]; then
	eww close-all && rm -rf "$FILE" && firefox &

elif [[ "$1" == "--telegram" ]]; then
	${EWW} close-all && rm -rf "$FILE" && telegram-desktop &

elif [[ "$1" == "--github" ]]; then
	xdg-open "https://github.com/YomiFlower" &

elif [[ "$1" == "--reddit" ]]; then
	${EWW} close-all && rm -rf "$FILE" &&  $cmd "https://reddit.com" &

elif [[ "$1" == "--code" ]]; then
	${EWW} close-all && rm -rf "$FILE" && code &

elif [[ "$1" == "--discord" ]]; then
	${EWW} close-all && rm -rf "$FILE" && discord &

elif [[ "$1" == "--spotify" ]]; then
	${EWW} close-all && rm -rf "$FILE" && spotify &
fi
